### PR TITLE
Add default slot values

### PR DESCRIPTION
**Pull request by andriygm**
https://github.com/user-attachments/assets/f259c7e1-d817-4b10-a705-42bcc6b0b5c0

### CODE REVIEW

**Comment by andriygm** [comment]
@dpastoor wanted your thoughts on deferring default value behavior to consumers -- for example the CLI uses the default value within the prompt itself, but the actual generate function has no default value handling. if there is no value supplied, generate will not provide a default even if one is set for a slot.

**Comment by dpastoor** [comment]
I think generate should remain "dumb" to being given that context object or whatever. It is up to each tool to determine how it needs to handle defaults in line with what the user expresses. For example, IMO even then the answer could literally be that for our boolean inputs, if bool == FALSE then we literally skip adding it to the context so its missing and then we get the missing tera behavior of falsey. 

This also makes sense around a webui vs cli vs flags etc all have slightly different ergonomics around how you express a default/missingness etc and even different defaults make sense. A cli with flags vs a prompt can have different default ergonomics that we can consider over time.

Does that answer the question?

**Review by dpastoor — APPROVED** [review]
nice - can we test this on the rprojectstarter with a default of true on renv for evidence then if that works LGTM

**Comment by andriygm** [comment]
default value is yes on R-project-starter when no value is entered
Screenshot 2024-10-16 at 11 30 09 AM
true generates renv line, false does not
Screenshot 2024-10-16 at 11 30 32 AM

**Pull request merged**
