### PR TITLE
Add dialoguer + single file mode

### PR DESCRIPTION
**Pull request by dpastoor**
This PR implements two things:

1. the ability to generate prompts for missing slots using the cli to collect input
2. the ability to use spackle on a single file

for missing slots, this makes it much more ergonomic not to need to type in all the flags/chase them down to remember which ones you need.

The single file spackle implementation will allow us to use single template files in non-spackle projects just as general templates where we can take advantage of tera + the slots concepts.

### CODE REVIEW

**Comment by dpastoor** [comment]
an example:

```
cargo run -- fill --file ../../../a2-ai-cloud/spackle-templates/go-cli/cmd/_template.go.j2t
```

```
---
[[slots]]
key = "cmd"
type = "String"
name = "command name"
description = "name of the command"

[[slots]]
key = "description"
type = "String"
name = "command name"
description = "name of the command"
---
import (
	"time"

	"github.com/spf13/cobra"
)

type {{cmd}}Opts struct {
}

type {{cmd}}Cmd struct {
	cmd  *cobra.Command
	opts *{{cmd}}Opts
}

func (opts *{{cmd}}Opts) Set() {
}

func (opts *{{cmd}}Opts) Validate() error {
	return nil
}

func new{{cmd | capitalize }}(cfg *rootOpts, opts *{{cmd}}Opts, args []string) error {
	// The HTTP Server
	startTime := time.Now()

	cfg.logger.Info("{{cmd}} finished", "duration", time.Since(startTime))
	return nil
}

func new{{cmd | capitalize }}Cmd(cfg *rootOpts) *{{cmd}}Cmd {
	{{cmd}}Cmd := &{{cmd}}Cmd{opts: &{{cmd}}Opts{}}
	cmd := &cobra.Command{
		Use:   "{{cmd}}",
		Short: "{{description}}",
		PreRunE: func(_ *cobra.Command, args []string) error {
			{{cmd}}Cmd.opts.Set()
			return {{cmd}}Cmd.opts.Validate()
		},
		RunE: func(_ *cobra.Command, args []string) error {
			return new{{cmd | capitalize }}(cfg, {{cmd}}Cmd.opts, args)
		},
	}
	{{cmd}}Cmd.cmd = cmd
	return {{cmd}}Cmd
}
```

given the contents of the template

```
🚰 spackle

✔ cmd · test
✔ description · a test command
import (
	"time"

	"github.com/spf13/cobra"
)

type {{cmd}}Opts struct {
}

type {{cmd}}Cmd struct {
	cmd  *cobra.Command
	opts *{{cmd}}Opts
}

func (opts *{{cmd}}Opts) Set() {
}

func (opts *{{cmd}}Opts) Validate() error {
	return nil
}

func new{{cmd | capitalize }}(cfg *rootOpts, opts *{{cmd}}Opts, args []string) error {
	// The HTTP Server
	startTime := time.Now()

	cfg.logger.Info("{{cmd}} finished", "duration", time.Since(startTime))
	return nil
}

func new{{cmd | capitalize }}Cmd(cfg *rootOpts) *{{cmd}}Cmd {
	{{cmd}}Cmd := &{{cmd}}Cmd{opts: &{{cmd}}Opts{}}
	cmd := &cobra.Command{
		Use:   "{{cmd}}",
		Short: "{{description}}",
		PreRunE: func(_ *cobra.Command, args []string) error {
			{{cmd}}Cmd.opts.Set()
			return {{cmd}}Cmd.opts.Validate()
		},
		RunE: func(_ *cobra.Command, args []string) error {
			return new{{cmd | capitalize }}(cfg, {{cmd}}Cmd.opts, args)
		},
	}
	{{cmd}}Cmd.cmd = cmd
	return {{cmd}}Cmd
}
```

ends up returning the following:

```
🚰 spackle

✔ cmd · test
✔ description · a test command
import (
	"time"

	"github.com/spf13/cobra"
)

type testOpts struct {
}

type testCmd struct {
	cmd  *cobra.Command
	opts *testOpts
}

func (opts *testOpts) Set() {
}

func (opts *testOpts) Validate() error {
	return nil
}

func newTest(cfg *rootOpts, opts *testOpts, args []string) error {
	// The HTTP Server
	startTime := time.Now()

	cfg.logger.Info("test finished", "duration", time.Since(startTime))
	return nil
}

func newTestCmd(cfg *rootOpts) *testCmd {
	testCmd := &testCmd{opts: &testOpts{}}
	cmd := &cobra.Command{
		Use:   "test",
		Short: "a test command",
		PreRunE: func(_ *cobra.Command, args []string) error {
			testCmd.opts.Set()
			return testCmd.opts.Validate()
		},
		RunE: func(_ *cobra.Command, args []string) error {
			return newTest(cfg, testCmd.opts, args)
		},
	}
	testCmd.cmd = cmd
	return testCmd
}
```

in this we can see the description and cmd's are filled in, plus the ability to use like capitalize as one of the built in tera templates to capitalize test --> Test

**Comment by dpastoor** [comment]
ok @andriygm for your hand-off:

A couple things going on - i literally did not implement collecting boolean/number values, just the input String types - so will want to actually finish that off.

For the single file work, I honestly do not feel that good about the code quality, and the fact that its really living in the CLI where I think there probably should be more logic pushed into the lib. We'll need to clean that up later, but I want to reorganize more of the cli/lib boundaries before we consider how this will roll this into an R package as well.

The other thing you'll see - I purposely removed hooks for now for the single file implementation. I think that is ok for now. I can see how a hook would still also be helpful, but not too worried about needing it immediately.

**Comment by andriygm** [comment]
@dpastoor let me know if this looks good at this point --  moved some logic around to keep the main CLI entry clean but there are definitely still improvements that can be made overall wrt CLI/lib boundary. also check out #10 for some small improvements there.

**Comment by andriygm** [comment]
also -- left a TODO, but do we want the single-file mode to also support writing its output? added logic for this but is currently commented.

**Comment by andriygm** [comment]
btw love the dialoguer, def a huge improvement. maybe we can flat out remove the --slot / --hook options all together

**Comment by dpastoor** [comment]
> btw love the dialoguer, def a huge improvement. maybe we can flat out remove the --slot / --hook options all together

I think we'll still want the flags for purposes of scripting/noninteractive contexts!

**Comment by dpastoor** [comment]
> also -- left a TODO, but do we want the single-file mode to also support writing its output? added logic for this but is currently commented.

yep for sure, for now when i've used it i just copy-paste from stdout into the file i care about. if we clean up the output to suppress any other extra noise we can also just emit clean printout if the template renders properly then make it pipeable

spackle fill -p file.j2t > output.txt

or detect if stdout is a pipe (i'm not sure if thats possible easily, I think it is though) and handle that

**Pull request merged**
